##################################################################
#
#
##################################################################
CC = gcc
CFLAGS = -Wall -O0 -g
CFLAGS = -std=gnu99
CFLAGS +=-DCONFIG_USE_DEBUG
CFLAGS += -I/usr/include/libxml2 -L/usr/lib/x86_64-linux-gnu
# CFLAGS += -I/usr/include/libxml2 -L/usr/lib/x86_64-linux-gnu -lxml2

PROGRAM = DramErrorInjector
OBJS = DRAMErrorInjector.o IOHCSMNRegAccessIfc.o \
		PCIEConfRegOpsIfc.o MSRRegOpsIfc.o DFRegOpsIfc.o \
		DhyanaSocConf.o APICRegOpsIfc.o \
		UMCRegOpsIfc.o EccErrInj.o EccErrAnls.o \
		MCARegOpsIfc.o TransSysAddrToDramChip.o TransDramChipToSysAddr.o \
		TransDramAddrHelperLib.o BaseHelperLib.o EccErrHelperLib.o \
		PreInjHandle.o ReqestHandler.o

#the main binary excutable file
all:$(PROGRAM)

$(PROGRAM):$(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $(PROGRAM) -lxml2

%.o:%.c
	$(CC) -c $(CFLAGS) $< -o $@

#remove the old tags file and recreate it, user `pwd` to create the tags in absolute path
ctags:
	@echo "Cleaning tags and recreate it ... "
	@rm -rf tags
	@ctags -R *.c *.h `pwd`

#remove the old cscope* files and recreate them
cscope:
	@echo "Cleaning cscope* and recreate them ..."
	@rm -rf cscope*
	@find `pwd` -path `pwd`/.git -prune -o -not -regex '.*\.\(png\|gif\)' -type f -a -name "*.[ch]" -o -name "*.[ch]pp" -o -name "*.js" -o -name "*.html" -o -name "*.asp" >> cscope.files 
	@cscope -Rbq -i cscope.files


#remove the old cscope* files and tags file, then recreate them
cscope:
	@echo "Cleaning cscope* and tags,then recreate them ..."

	@rm -rf tags
	@rm -rf cscope*

	@ctags -R *.c *.h `pwd`

	@find `pwd` -path `pwd`/.git -prune -o -not -regex '.*\.\(png\|gif\)' -type f -a -name "*.[ch]" -o -name "*.[ch]pp" -o -name "*.js" -o -name "*.html" -o -name "*.asp" >> cscope.files 
	@cscope -Rbq -i cscope.files


#clean the intermediates
clean:
	@echo "Cleaning objs ..."
	@rm -rf $(OBJS) $(PROGRAM)

#PHONY target
.PHONY: clean ctags cscope